//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoWise.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoWiseEntities : DbContext
    {
        public EcoWiseEntities()
            : base("name=EcoWiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<EmployeeCrew> EmployeeCrews { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<EmployeeWorkTime> EmployeeWorkTimes { get; set; }
        public virtual DbSet<JobDetail> JobDetails { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobSegment> JobSegments { get; set; }
        public virtual DbSet<MaterialPurchas> MaterialPurchases { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Employee_EmployeeCrews> Employee_EmployeeCrews { get; set; }
        public virtual DbSet<Employee_EmployeeTypes> Employee_EmployeeTypes { get; set; }
    }
}
