//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoWise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_EmployeeCrews
    {
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EmployeeCrewId { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EmployeeCrew EmployeeCrew { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
