//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoWise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public string Level { get; set; }
        public string Wall { get; set; }
        public string Type { get; set; }
        public Nullable<int> OptionNo { get; set; }
        public string Description { get; set; }
        public decimal Length { get; set; }
        public decimal Height { get; set; }
        public decimal Depth { get; set; }
        public int Multiple { get; set; }
        public string Material { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Strokes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
